sudo: required
services:
  - docker

before_install:
  - docker build -t zefhon/docker-react -f Dockerfile.dev .

script:
  - docker run zefhon/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucker_name: ""
  bucket_path: "docker"
  on:
    branch: master
  acces_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
   secure: "$AWS_SECRET_KEY"
